### ISSUE TITLE
Images not behaving on product pages

### ISSUE THREAD

**Issue by matthewcrisp** [matthewcrisp/drumhut#1]
In line 48 of product.hbs (/src/templates/layouts), I've been trying to play with the sizes of the images that appear on each individual djembe page and nothing seems to be working. Would like them to fit nicely across the width of the col-md-8 space but not be too tall. Nothing I do changes how they look in the browser though.

**Comment by danielcrisp** [comment]
It's looking amazing!

**Comment by danielcrisp** [comment]
Ok it now looks like this

![image](https://cloud.githubusercontent.com/assets/1104814/9911275/408844f2-5c99-11e5-9e15-9c61425f08c3.png)

But remember an image will maintain its aspect ratio. So if you are using a portrait image it will always be taller than it is wide. Of course you can force it to a different ratio but it will look squashed.

Also its not that easy to align the image vertically and the browser (obviously) doesn't know which bit of the image looks nicest when deciding where to crop.

So... the best solution is to crop your images to fit the website and make sure images that are grouped in a slideshow are cropped to the same size / ratio

**Comment by danielcrisp** [comment]
If you want to tweak the max height, just change this value:

https://github.com/matthewcrisp/drumhut/blob/master/website/src/assets/css/drumhut.css#L41

``` css
.slide-wrapper {
    max-height: 500px;
}
```

If you want the images to be portrait just use a larger number

**Comment by matthewcrisp** [comment]
Thank you!!

If I'm wanting to use the same image in multiple places, but different crops/aspects, should I just upload it differently each time or is it better (for caching reasons?) to use the same one and code the various crops? Also what max pixel dimensions would you recommend for full width images (like the homepage)?

Thanks again!

**Comment by danielcrisp** [comment]
Its better for the user to only have to download each picture (of a particular dimension) once, but I wouldn't worry about that for now.

I'd say crop the images as you wish and use the exact crop for each particular location, rather than trying to make one size fit all.

And in terms of dimensions it depends on your theme really, but I guess 1920x1080 would be sensible. Perhaps a bit taller. What size did the original theme use?

**Comment by matthewcrisp** [comment]
I've tried resizing images to fit the space and I've tried copying the dimensions used in the bootstrap template, but neither seems to work. On every individual product page, it just looks weird and the images fade in and out of the browser (like it thinks there are more images in the slideshow than there really are). I'm a bit stumped by this.

But apart from this and the videos, it's nearly finished!

**Comment by danielcrisp** [comment]
Have you pushed your latest code?

**Comment by danielcrisp** [comment]
Ok, there is a bug with the slider library (https://github.com/nicinabox/superslides/issues/124) that means if there is only one image it gets a bit confused.

So I've updated the JS to detect the number of images before activating the slider... seems better now
