### ISSUE TITLE
Need a little bit of Snipcart help.

### ISSUE THREAD

**Issue by matthewcrisp** [matthewcrisp/drumhut#11]
I thought I'd be able to do everything myself, but I've tripped at this point: http://docs.snipcart.com/configuration/json-crawler

Not quite sure what it's asking me to do. Sounds like it wants me to make a new json file that points their crawler to my various {products}.json files. Have I understood that correctly? And if so, where do I put _that_ json file?

Other than this, it's all almost ready to go!

**Comment by danielcrisp** [comment]
I think it is saying that, if you prefer, you can point this attribute at a JSON file instead:

``` html
    data-item-url="http://myapp.com/products/bacon"
```

If their crawler detects that the URL responds with a Content-Type header of `application/json` rather than `text/html` (a page) then it will parse it as JSON, _but_ it must have the correct structure.

So unless you're getting a specific error I don't think this concerns you does it? Or maybe you can just _point_ to your various {products}.json files from the `data-item-url` attributes

**Comment by matthewcrisp** [comment]
I am getting an error when I finalise an order and it sounds like the HTML crawler is the problem. using the HTML version, I have to put `data-item-url="./{{filename}}.html"`, which I think is what's causing it.

Will give it a shot this way and let you know!

**Comment by matthewcrisp** [comment]
> Or maybe you can just point to your various {products}.json files from the data-item-url attributes

Trying to do this, but I can't get it to work. Here's the error message I get:
![snipcart](https://cloud.githubusercontent.com/assets/12495344/19117217/25e1014c-8b10-11e6-8a1f-c92d1c6c6f9f.jpg)

If I put `data-item-url= some json file`, where should this json file be and what should be in the url field of that json? Is there some way I can be clever and get it to call djembes.json and say ./{{filename}}.html is the url. Or will it be quicker to write each url by hand? Although I just tried the latter for one drum and still got the error!

**Comment by matthewcrisp** [comment]
No urgency on this. I need to head out for the rest of the evening now anyway and probably can't carry on with this until Monday.

**Comment by danielcrisp** [comment]
Where are you running this? I don't see it on the published site...

Bear in mind that their crawler won't be able to access your local version because it only exists on your local network.

**Comment by matthewcrisp** [comment]
Okay, it's live now, but I'm still getting the same error. I still don't fully understand the chain of what needs to point to what for the JSON crawler to work.

**Comment by danielcrisp** [comment]
So you don't see this?

![image](https://cloud.githubusercontent.com/assets/1104814/19183417/12b7fcfe-8c70-11e6-9d00-56f5111ef004.png)

**Comment by matthewcrisp** [comment]
I get the error after this button: 
![snipcart](https://cloud.githubusercontent.com/assets/12495344/19186241/3faec5be-8c7d-11e6-850b-586078d47f3e.jpg)

**Comment by danielcrisp** [comment]
I see this in the console

![image](https://cloud.githubusercontent.com/assets/1104814/19186898/5a3efac2-8c80-11e6-9787-10ce846b5d29.png)

Looks like you've got `.html.html` somewhere

**Comment by danielcrisp** [comment]
Yeah I see it on your button

![image](https://cloud.githubusercontent.com/assets/1104814/19186920/7b9779e2-8c80-11e6-9570-4c57cd0bca63.png)

**Comment by danielcrisp** [comment]
https://github.com/matthewcrisp/drumhut/blob/master/website/src/templates/layouts/product-djembe.hbs#L42

**Comment by matthewcrisp** [comment]
Got rid of the `.html`, but it's still giving me the same error.

**Comment by danielcrisp** [comment]
New error:

![image](https://cloud.githubusercontent.com/assets/1104814/19187330/c435f5a0-8c82-11e6-8be9-144aa53112a0.png)

Remove the .

**Comment by matthewcrisp** [comment]
Still get the error!

**Comment by danielcrisp** [comment]
Now it's saying this:

![image](https://cloud.githubusercontent.com/assets/1104814/19187440/5c4da70c-8c83-11e6-86c6-4144f8ca4a27.png)

I suspect it is because it is trying to access the URL _without_ `www.` which I don't think works...

Maybe you have a setting somewhere in the admin on Snipcart where you can tell it to use www.thedrumhut.co.uk instead of just thedrumhut.co.uk

Alternatively you could fix it by using an absolute URL in your `data-item-url` attribute, e.g.

``` html
data-item-url="http://www.thedrumhut.co.uk/djembe-maxwell.html"
```

**Comment by matthewcrisp** [comment]
Tried it with the absolute URL and it hasn't fixed it

**Comment by danielcrisp** [comment]
Thank you for your order!

![image](https://cloud.githubusercontent.com/assets/1104814/19187631/5f0ad694-8c84-11e6-960d-b60860679e84.png)

Try emptying your basket first

**Comment by matthewcrisp** [comment]
AMAZING!!! Thank you!
