### ISSUE TITLE
Website has disappeared!

### ISSUE THREAD

**Issue by matthewcrisp** [matthewcrisp/drumhut#14]
It's just vanished off the face of the internet. I've tried redeploying, the CNAME file is correct, no issues according to the godaddy dashboard. I've no idea what's causing it!

Help!

**Comment by danielcrisp** [comment]
I think we need an [URGENT] label

**Comment by danielcrisp** [comment]
@matthewcrisp 

It looks like your domain name has expired: https://who.is/whois/thedrumhut.co.uk

Login to your registrar and re-register it. Often there is a holding period when you can re-register it and no-one else can. If that has elapsed then anybody can buy it!

Quick! Quick! Quick!

**Comment by matthewcrisp** [comment]
Okay, I think I've fixed it. Domain is renewed. The site is still down though. Could that just be lag on the registrar's end?

**Comment by danielcrisp** [comment]
Yep, they usually say it takes about 24-48 hours for changes to propagate around the world’s DNS servers.

It’s already back up for me though
