### ISSUE TITLE
Key verification issues

### ISSUE THREAD

**Issue by matthewcrisp** [matthewcrisp/drumhut#15]
I keep getting this every time I try to deploy.
```
Pushing gh-pages to git@github.com:matthewcrisp/drumhut.git
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 Use --force to continue.

Aborted due to warnings.
```

I've tried creating a new SSH key, but it didn't work. The old ones that used to work are still there.

I reinstalled GitHub Desktop, and Powershell recently and this started to happen then. I've not tried using --force yet. Wanted to check with you first!

**Comment by danielcrisp** [comment]
I would try this answer first, before using `--force`

https://stackoverflow.com/a/29380765/3191425

**Comment by matthewcrisp** [comment]
That worked, thank you!
