### ISSUE TITLE
Line breaks (and other html) within JSON strings not working in browser.

### ISSUE THREAD

**Issue by matthewcrisp** [matthewcrisp/drumhut#2]
If you look at line 226 of djembes.json, I've tried to embed some html tags in the json data. Googling suggests it's possible if you escape all the correct characters, but it doesn't seem to be working for me.

I can workaround the line breaks by adding a new data field and putting {{ new field }} underneath the description field in the .hbs file, but it'd be easier if it were possible to have <br> work within the string. Am I missing something simple here?

**Comment by danielcrisp** [comment]
Its not obvious but I think you just need to change your output variable so it uses three braces instead of two.

i.e. `{{{ field }}}` instead of `{{ field }}`

This tells the parser to expect html, rather than escaping it

**Comment by danielcrisp** [comment]
Is this ok now? Closing this issue... reopen it if its still not working for you
