### ISSUE TITLE
Confused about product pages

### ISSUE THREAD

**Issue by matthewcrisp** [matthewcrisp/drumhut#3]
I'm trying to alter the structure of things so that product page for djembes follows it's own tailor made layout (currently product.hbs) and for accessories, dunun and anything else I decide to sell, I can make a new hbs file to dictate the layout separately for each type of item.

But I can't see where the pages for individual products are told which layout to use. It seems to be product.hbs by default for them all and I can't find where to change it.

I think I can make the layout files myself, but could you make the right pages point to the right ones for me?

Thank you!

**Comment by danielcrisp** [comment]
Maybe you're looking for this?

https://github.com/matthewcrisp/drumhut/blob/master/website/Gruntfile.js#L87-L95

**Comment by danielcrisp** [comment]
Do you mean you want to do something like this? So you can have a different layout for each type of item? [untested]

``` javascript

    assemble: {
      options: {
          flatten: true,
          assets: '<%= config.dist %>/assets',
          layout: 'default.hbs',
          layoutdir: '<%= config.src %>/templates/layouts/',
          data: '<%= config.src %>/data/*.{json,yml}',
          partials: '<%= config.src %>/templates/partials/*.hbs',
          plugins: ['assemble-contrib-permalinks','assemble-contrib-sitemap']
      },
      pages: {
        files: {
            '<%= config.dist %>/': ['<%= config.src %>/templates/pages/*.hbs']
        }
      },
      djembes: {
        options: {
          layout: 'djembes.hbs',
          pages: grunt.file.readJSON('src/data/djembes.json')
        },
        files: {
            '<%= config.dist %>/': ['<%= config.src %>/templates/pages/dummy.hbs']
        }
      },
      accessories: {
        options: {
          layout: 'accessories.hbs',
          pages: grunt.file.readJSON('src/data/accessories.json')
        },
        files: {
            '<%= config.dist %>/': ['<%= config.src %>/templates/pages/dummy.hbs']
        }
      }
    },
```

**Comment by danielcrisp** [comment]
Closing... reopen if you are still having problems
