### ISSUE TITLE
Some tweaks

### ISSUE THREAD

**Issue by danielcrisp** [matthewcrisp/drumhut#4]
I've tidied things up a bit:
- Removed unused templates
- Renamed files to include their type (to prevent clashes, plus good for search engines), e.g. `djembe-alseny1.html` instead of `alseny1.html`
- Added a `title` property to the djembe, dunun and accessory data files so you can specify the page title (v. important for search engines)

![image](https://cloud.githubusercontent.com/assets/1104814/11106019/c1b8c44a-88ca-11e5-99c1-72af76ca57a4.png)
- Added an Enquire button to each product listing that opens a blank email to you with a helpful subject

![image](https://cloud.githubusercontent.com/assets/1104814/11106022/caebbc48-88ca-11e5-86fe-846c709eb87d.png)

![image](https://cloud.githubusercontent.com/assets/1104814/11106029/d789555a-88ca-11e5-8730-175091c67e0c.png)
- Added an option to the data files to show / hide said Enquire button (`showEnquireButton`)

**Comment by matthewcrisp** [comment]
Thank you! I'm having trouble merging all of this with the version on my desktop. There were a few changes (mostly correcting typos, so nothing major) that'd I'd not pushed yet, so I'm getting conflict issues when I try to commit things. Git marked all the conflicts with <<<<<< ======== >>>>>> those things and I think I've found them all and changed them to how they should be, but it's still not letting me sync or commit.

Any ideas?

**Comment by danielcrisp** [comment]
Once you've fixed the conflicts you will need to commit, pull and then push

Do you use the GUI?
