### ISSUE TITLE
Transparent png blocking a link

### ISSUE THREAD

**Issue by matthewcrisp** [matthewcrisp/drumhut#6]
I've tried to set everything up so that when I toggle "sold": true/false, in djembes.json it will put a sold stamp over the image on the Djembes page and duplicate the listing in 'The Archive'. It's worked in every respect except that sold.png, which is the stamp image, blocks the image below it from being a clickable link. Is it possible to put a z index on the <a> tag beneath it to bring the link in front of the png? I'm just not sure where to find the code for the {{ product-link this }} stuff, so I don't know how to change anything!

Thank you :)

**Comment by danielcrisp** [comment]
Fixed.

The trick is to have the `img` inside the `a`

I've added it to the `product-link.hbs` partial, so it will automatically appear everywhere
