### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by matthewcrisp** [matthewcrisp/drumhut#7]
I keep getting the following error when I try to push to the gh-pages subtree:
![push error](https://cloud.githubusercontent.com/assets/12495344/11531239/482129a4-98f3-11e5-80d7-06cca7daa47a.jpg)

What am I doing wrong?

**Comment by danielcrisp** [comment]
I think the clue is in the error message ;-)

```
You need to run this command from the toplevel of the working tree.
```

Try moving up a directory to the root of the repo then run the command again

```
cd ../
```
